version: '3.1'

services:
    pg:
        image: postgres
        restart: 'always'
        expose:
            - '5432'
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=prisma
            - POSTGRES_HOST_AUTH_METHOD=trust
            # - POSTGRES_DB=$POSTGRES_DB
            # - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            # - POSTGRES_USER=$POSTGRES_USER
        # volumes:
        #     - "./db/data:/var/lib/postgresql/data"
        #     - "./db/init:/docker-entrypoint-initdb.d"
