version: '3.9'

services:
    db:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: admin
